config/routes.rb
Rails.application.routes.draw do
  root 'welcome#hello'
  resources :users
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  resources :book_shelves
  resources :genres, only: [:index, :show]
  resources :reviews
  resources :books, only: [:new, :create, :index, :show]
  resources :authors, only: [:index, :show]
  resources :shelves
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :shelves
  has_many :reviews
  validates :name, presence: true
  validates :password, presence: true
  validates :name, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    # byebug
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:alert] = "there was an error"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
    if session["user_id"] && @user == current_user
      render :show
    else
      redirect_to root_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      session.delete :user_id
      @user.destroy
    end
    redirect_to root_path
  end

private

def user_params
  params.require(:user).permit(:name, :password, :password_confirmation)
end

end

app/views/users/edit.html.erb
<%= form_for @user do |f|%>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>
<%= f.submit  %>
<%end %>
<br>
<%= link_to "Home", root_path %>

app/views/users/new.html.erb
<%=flash[:alert]%>
<div class="form-container">
Sign Up For Googreads Today!
<%= form_for @user do |f|%>
<%= f.label :name %>
<%= f.text_field :name, required: true%>
<br>
<%= f.label :password %>
<%= f.password_field :password, required: true %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, required: true %>
<br>
<%= f.submit  %>
<%end %>
</div>
<br>

app/views/users/show.html.erb
Hi <%=@user.name%><br><br>
List of your shelves:<br><br>
<%@user.shelves.each do |shelf| %>
  <strong>Shelf name: <%=shelf.name%></strong><br>
  <%shelf.books.each do |book|%>
    <%=book.title%> by <%=book.author.name%><Br>
    <%book.genres.each do |genre|%>
       Genre:<%=genre.name%><br>
    <%end%>
    <%if book.reviews.length > 0%>
      Reviews:<br>
      <%book.reviews.each do |review| %>
        Rating: <%=review.rating%><br>
        Content: <%=review.content%><br>
      <%end%><br>
    <%end%><br>
  <%end%>
  <br>
<%end%>

<%= form_tag logout_path do %>
<%= submit_tag "Logout" %>
<% end %>

<%= link_to "Edit Account", edit_user_path %>

<%= form_tag user_path(@user), method: "delete" do%>
  <%= submit_tag "Delete account" %>
<% end %>

<br>
<%= link_to "Home", root_path %>